config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_for :users, controllers: {
    sessions:       'users/sessions', 
    registrations:  'users/registrations', 
    passwords:      'users/passwords', 
    confirmations:  'users/confirmations', 
    unlocks:        'users/unlocks'
  }
  
  resources :test_papers do 
    member do 
      get :preview_test
      post :start_test_paper
    end
  end

  namespace :admin do
    resources :test_papers 
    resources :submissions, only: [:index, :show]
  end

  resources :multiple_choice_questions do 
  end
  resources :user_response_values

  get '/load_question' => 'multiple_choice_questions#load_question'
  get '/load_previous_question' => 'multiple_choice_questions#load_previous_question'
  get '/load_next_question' => 'multiple_choice_questions#load_next_question'
  get '/question_marked_for_review' => 'user_response_values#question_marked_for_review'
  get '/test_submission' => 'test_papers#test_submission'
  get '/instruction' => "home#instruction"
end

app/views/admin/index.html.erb
<div class="container-fluid mt-4">
  <div class="row">
    <div class="col-md-6">
      <h1>Test Papers</h1>
    </div>
    <div class="col-md-6">
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "btn btn-danger float-right" if admin_signed_in? %>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date to take test</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @test_papers.each do |test_paper| %>
        <tr>
          <td><%= test_paper.name %></td>
          <td><%= test_paper.date_to_take_test %></td>
          <% if user_signed_in? %>
            <td><%= link_to 'Show', test_paper, class: "btn btn-info" %></td>
          <% else %>
            <td><%= link_to 'Show', admin_test_paper_path, class: "btn btn-info" %></td>
            <td><%= link_to 'Edit', edit_admin_test_paperpath(test_paper), class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', admin_test_paper, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Test Paper', new_admin_test_paper_path, class: "btn btn-success" if !user_signed_in? %>
</div>

app/views/admin/new.html.erb
<div class="container">
  <div class="col-12">
    <h1>New Test Paper</h1>
    <%= render 'form', test_paper: @test_paper %>
    <%= link_to 'Back', admin_test_papers_path %>
  </div>
</div>

app/views/admin/show.html.erb
<div class="container">
  <div class="col-md-8 offset-md-2">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Name:</strong>
      <%= @test_paper.name %>
    </p>
    <p>
      <strong>Date to take test:</strong>
      <%= @test_paper.date_to_take_test %>
    </p>

    <%= link_to 'Edit', edit_admin_test_paper_path(@test_paper), class: "btn btn-secondary btn-lg" %> 

    <%= link_to 'Back', admin_test_papers_path, class: "btn btn-primary btn-lg" %>

    <%= link_to 'Start Test', start_test_paper_test_paper_path(@test_paper), class: "btn btn-info btn-lg", method: :post %>
  </div>
</div>