config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_for :users, controllers: {
    sessions:       'users/sessions', 
    registrations:  'users/registrations', 
    passwords:      'users/passwords', 
    confirmations:  'users/confirmations', 
    unlocks:        'users/unlocks'
  }
  
  resources :test_papers do 
    member do 
      get :preview_test
      post :start_test_paper
    end
  end

  namespace :admin do
    resources :test_papers 
    resources :submissions, only: [:index, :show]
  end

  resources :multiple_choice_questions do 
  end
  resources :user_response_values

  get '/load_question' => 'multiple_choice_questions#load_question'
  get '/load_previous_question' => 'multiple_choice_questions#load_previous_question'
  get '/load_next_question' => 'multiple_choice_questions#load_next_question'
  get '/question_marked_for_review' => 'user_response_values#question_marked_for_review'
  get '/test_submission' => 'test_papers#test_submission'
  get '/instruction' => "home#instruction"
end

app/models/test_paper.rb
class TestPaper < ApplicationRecord
  has_many :submissions
  has_many :multiple_choice_questions, inverse_of: :test_paper
  accepts_nested_attributes_for :multiple_choice_questions, reject_if: :all_blank, allow_destroy: true
end

app/controllers/admin/test_papers_controller.rb
class Admin::TestPapersController < ApplicationController
  layout 'admin'
  before_action :set_test_paper, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:preview_test, :start_test_paper]

  def index
    @test_papers = TestPaper.all
  end

  def show
  end

  def new
    @test_paper = TestPaper.new
  end

  def edit
  end

  def create
    @test_paper = TestPaper.new(test_paper_params)

    respond_to do |format|
      if @test_paper.save
        format.html { redirect_to admin_test_paper_path(@test_paper), notice: 'Test paper was successfully created.' }
        format.json { render :show, status: :created, location: @test_paper }
      else
        format.html { render :new }
        format.json { render json: @test_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @test_paper.update(test_paper_params)
        format.html { redirect_to admin_test_paper_path(@test_paper), notice: 'Test paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_paper }
      else
        format.html { render :edit }
        format.json { render json: @test_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @test_paper.destroy
    respond_to do |format|
      format.html { redirect_to admin_test_papers_url, notice: 'Test paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview_test
    @test_paper = TestPaper.find(params[:id])
    @mcq = @test_paper.multiple_choice_questions.first
    @submission = Submission.find(params[:submission])
  end

  def start_test_paper
    @test_paper = TestPaper.find(params[:id])
    @submission = Submission.create(user_id: current_user.id, test_paper_id: @test_paper.id)
    redirect_to preview_test_test_paper_path(@test_paper, submission: @submission.id)
  end

  def test_submission
    @test_paper = TestPaper.find(params[:test_paper_id])
  end

  def total_submission
    @submissions = Submission.all
  end

  private
    
    def set_test_paper
      @test_paper = TestPaper.find(params[:id])
    end

    def test_paper_params
      params.require(:test_paper).permit!
    end

end

app/controllers/test_papers_controller.rb
class TestPapersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!, only: [:create, :new, :edit, :update, :destroy]
  before_action :set_test_paper, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:preview_test, :start_test_paper]

  def index
    @test_papers = TestPaper.all
  end

  def show
  end

  def new
    @test_paper = TestPaper.new
  end

  def edit
  end

  def create
    @test_paper = TestPaper.new(test_paper_params)

    respond_to do |format|
      if @test_paper.save
        format.html { redirect_to @test_paper, notice: 'Test paper was successfully created.' }
        format.json { render :show, status: :created, location: @test_paper }
      else
        format.html { render :new }
        format.json { render json: @test_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @test_paper.update(test_paper_params)
        format.html { redirect_to @test_paper, notice: 'Test paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_paper }
      else
        format.html { render :edit }
        format.json { render json: @test_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @test_paper.destroy
    respond_to do |format|
      format.html { redirect_to test_papers_url, notice: 'Test paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview_test
    @test_paper = TestPaper.find(params[:id])
    @mcq = @test_paper.multiple_choice_questions.first
    @submission = Submission.find(params[:submission])
  end

  def start_test_paper
    @test_paper = TestPaper.find(params[:id])
    @submission = Submission.create(user_id: current_user.id, test_paper_id: @test_paper.id)
    redirect_to preview_test_test_paper_path(@test_paper, submission: @submission.id)
  end

  def test_submission
    @test_paper = TestPaper.find(params[:test_paper_id])
  end

  private
    
    def set_test_paper
      @test_paper = TestPaper.find(params[:id])
    end

    def test_paper_params
      params.require(:test_paper).permit!
    end

end

app/helpers/test_papers_helper.rb
module TestPapersHelper
end

app/views/test_papers/_form.html.erb
<%= form_for @test_paper do |f| %>
  <% if @test_paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_paper.errors.count, "error") %> prohibited this test_paper from being saved:</h2>

      <ul>
      <% @test_paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date_to_take_test %>
    <%= f.date_field :date_to_take_test, class: "form-control" %>
  </div>

  <div id="multiple_choice_questions" class="nested-form-area">
    <%= f.fields_for :multiple_choice_questions do |mcq| %>
      <%= render 'multiple_choice_question_fields', f: mcq %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add MCQ', f, :multiple_choice_questions, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success btn-lg mt-4 mb-3" %>
  </div>
<% end %>

app/views/test_papers/_multiple_choice_question_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-sm-7">
      <div class="form-group">
        <%= f.text_area :question, class: "form-control", placeholder: "Write Question Here", rows: "3" %>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="form-group">
        <%= f.number_field :sequence_number, class: "form-control", placeholder: "Write S. No" %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="form-group">
        <%= link_to_remove_association "Remove MCQ", f, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  <div id="mcq_options">
    <%= f.fields_for :mcq_options do |option| %>
      <%= render 'mcq_option_fields', f: option %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Option', f, :mcq_options, class: "btn btn-primary" %>
      <hr>
    </div>
  </div>
</div>

app/views/test_papers/edit.html.erb
<div class="container">
  <div class="col-12">
    <h1>Editing Test Paper</h1>
    <%= render 'form', test_paper: @test_paper %>
    <%= link_to 'Show', @test_paper %> |
    <%= link_to 'Back', test_papers_path %>
  </div>
</div>

app/views/test_papers/index.html.erb
<div class="container-fluid mt-4">
  <div class="row">
    <div class="col-md-6">
      <h1>Test Papers</h1>
    </div>
    <div class="col-md-6">
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "btn btn-danger float-right" if admin_signed_in? %>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date to take test</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @test_papers.each do |test_paper| %>
        <tr>
          <td><%= test_paper.name %></td>
          <td><%= test_paper.date_to_take_test %></td>
          <% if user_signed_in? %>
            <td><%= link_to 'Show', test_paper, class: "btn btn-info" %></td>
          <% else %>
            <td><%= link_to 'Show', test_paper, class: "btn btn-info" %></td>
            <td><%= link_to 'Edit', edit_test_paper_path(test_paper), class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', test_paper, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Test Paper', new_test_paper_path, class: "btn btn-success" if !user_signed_in? %>
</div>

app/views/test_papers/new.html.erb
<div class="container">
  <div class="col-12">
    <h1>New Test Paper</h1>
    <%= render 'form', test_paper: @test_paper %>
    <%= link_to 'Back', test_papers_path %>
  </div>
</div>

app/views/test_papers/preview_test.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <div class="text-center mr-4 mb-5">
        <%= link_to "Submit Test", test_submission_path(test_paper_id: @test_paper.id), class: "btn btn-success float-right" %>
      </div>
    </div>
    <div class="col-12 mt-5">
      <div class="row" id="test_question_area">
        <div class="col-md-9">
          <div class="card custom-card">
            <div class="card-body">
              <div>
                <%= form_for :user_response, url: :user_response_values, method: :post, remote: true do |f| %>
                  <%= f.hidden_field :submission_id, value: @submission.id %>
                  <%= f.hidden_field :multiple_choice_question_id, value: @mcq.id %>
                  <%= f.hidden_field :user_id, value: current_user.id %>
                  <%#= f.hidden_field :already_answered, value: true if check_if_answered(current_user.id, @mcq.id) %>
                  <%= f.hidden_field :user_response_value_id, value: get_user_response_value(current_user.id, @mcq.id).id if get_user_response_value(current_user.id, @mcq.id).present?  %>
                  <label><strong><%= @mcq.sequence_number %>. </strong> <%= @mcq.question %></label>
                  <% @mcq.mcq_options.each do |mcq_opt| %>
                    <% if check_if_answered(current_user.id, @mcq.id) %>
                      <div class="form-group">
                        <% if user_selected_option(current_user.id, @mcq.id) == mcq_opt.option %>
                          <%= f.radio_button @mcq.question, mcq_opt.option, checked: true %>
                        <% else %>
                          <%= f.radio_button @mcq.question, mcq_opt.option %>
                        <% end %>
                        <%= f.label mcq_opt.option %>
                      </div>
                    <% else %>
                      <div class="form-group">
                        <%= f.radio_button @mcq.question, mcq_opt.option %>
                        <%= f.label mcq_opt.option %>
                      </div>
                    <% end %>
                  <% end %>
                  <% if @mcq.id == @test_paper.multiple_choice_questions.first.id %>
                    <%= link_to "Previous", "", class: "btn btn-primary disabled" %>
                  <% else %>
                    <%= link_to "Previous", load_previous_question_path(mcq_id: @mcq.id, submission: @submission.id), class: "btn btn-primary", remote: true %>
                  <% end %>
                  <% if @mcq.id == @test_paper.multiple_choice_questions.last.id %>
                    <%= f.submit "Save", class: "btn btn-success" %>
                  <% else %>
                    <%= f.submit "Save & Next", class: "btn btn-success" %>
                  <% end %>
                  <%= link_to "Marked for Review & Next", question_marked_for_review_path(mcq_id: @mcq.id, submission_id: @submission.id), remote: true, class: "btn btn-primary btn-indigo" %>
                  <% if @mcq.id == @test_paper.multiple_choice_questions.last.id %>
                    <%= link_to "Next", "", class: "btn btn-info disabled" %>
                  <% else %>
                    <%= link_to "Next", load_next_question_path(mcq_id: @mcq.id, submission: @submission.id), class: "btn btn-info", remote: true %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <% @test_paper.multiple_choice_questions.each do |mcq| %>
            <% if mcq.question_user_statuses.present? && current_user.question_user_statuses.present? %>
              <% user_id = current_user.id %>
              <% mcq_id = mcq.id %>
              <% if question_status(user_id, mcq_id) == "Answered" %>
                <%= link_to mcq.sequence_number, load_question_path(mcq_id: mcq.id, submission: @submission.id), class: "btn btn-success btn-mark mb-2", remote: true %>
              <% elsif question_status(user_id, mcq_id) == "Marked for Review" %>
                <%= link_to mcq.sequence_number, load_question_path(mcq_id: mcq.id, submission: @submission.id), class: "btn btn-indigo btn-mark mb-2", remote: true %>
              <% else %>
                <%= link_to mcq.sequence_number, load_question_path(mcq_id: mcq.id, submission: @submission.id), class: "btn btn-secondary btn-mark mb-2", remote: true %>
              <% end %>
            <% else %>
              <%= link_to mcq.sequence_number, load_question_path(mcq_id: mcq.id, submission: @submission.id), class: "btn btn-secondary btn-mark mb-2", remote: true %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/test_papers/show.html.erb
<div class="container">
  <div class="col-md-8 offset-md-2">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Name:</strong>
      <%= @test_paper.name %>
    </p>
    <p>
      <strong>Date to take test:</strong>
      <%= @test_paper.date_to_take_test %>
    </p>
    <%= link_to 'Back', test_papers_path, class: "btn btn-primary btn-lg" %>

    <%= link_to 'Start Test', start_test_paper_test_paper_path(@test_paper), class: "btn btn-info btn-lg", method: :post %>
  </div>
</div>